### ISSUE TITLE
Renaming Routes

### ISSUE THREAD

**Issue by bejucoo** [JPfeP/AddRoutes#13]
Hello,

thank you very much for this piece of software, I've wanted to use Blender as a real time VJing tool and this really helps a lot. I want to know if route names/labels can be changed? Numbers are just fine for a couple of routes but it starts to get confusing with a lot of them.

![Screenshot_20220903_213837](https://user-images.githubusercontent.com/19770567/188294689-53d4dadd-fcdb-402d-bd67-45c0d6397b7e.png)

**Comment by JPfeP** [comment]
Yes,  naming route is possible already but to simplify the layout the name input box is hidden by default. 
You have to enable it in the Tools section "show name settings" in the extra routes parameters.

**Comment by bejucoo** [comment]
Thank you @JPfeP. Also, not related, but I think it'd be useful to add an offline documentation file to the downloadable .zip.
