### ISSUE TITLE
Adding and Removing Routes give error pop out

### ISSUE THREAD

**Issue by enzyme69** [JPfeP/AddRoutes#2]
<img width="819" alt="Screen Shot 2020-04-16 at 11 31 14 am" src="https://user-images.githubusercontent.com/3952687/79404742-e120b480-7fd5-11ea-80bd-681d41033881.png">

**Comment by JPfeP** [comment]
This is a side effect from the add-on failing to start due to the lack of the libraries. Most probably. Hopefully you managed to pass this step.

**Comment by JPfeP** [comment]
Install by yourself the related libs or use the ready-to-go zip file (see description project page)
