### ISSUE TITLE
Only one route send osc data in python evaluation

### ISSUE THREAD

**Issue by dewiweb** [JPfeP/AddRoutes#3]
Hello,

I'm looking for using Addroutes to send real coordinates of object with matrix_world  function in python evaluate mode :
bpy.data.objects['Cube'].matrix_world.translation
It works for one object but if i create a second route for a second object and make both send osc, only the first route really sends values!

**Comment by JPfeP** [comment]
I think I found the problem, it's a break instruction that was left by mistake probably after the recent changes I made to handle more gracefully sending errors. 

You can see it in ligne 447 of the osc.py file. This line was preventing any further iteration of the sending routes ensemble.

You might want to remove it manually on your own copy to fix temporarily the issue. I will update the github later this week, I am working on some substantial changes.

**Comment by JPfeP** [comment]
I think it should be fine now. I just released v0.29 on the official site. You can use the link in the documentation page, it's updated.
BTW, this maintenance release includes another bug fix (recording OSC routes was broken).

**Comment by dewiweb** [comment]
Hello, you can mark this issue resolved.
It works now!
Many thanks
