### ISSUE TITLE
Cannot enable addon: "ModuleNotFoundError: No module named 'rtmidi._rtmidi'"

### ISSUE THREAD

**Issue by imedina7** [JPfeP/AddRoutes#5]
Blender version: 2.83.1

`Traceback (most recent call last):`
`  File "/usr/share/blender/2.83/scripts/modules/addon_utils.py", line 351, in enable`
`    mod = __import__(module_name)`
`  File "/home/dave/.config/blender/2.83/scripts/addons/AddRoutes/__init__.py", line 55, in <module>`
`    from . import data`
`  File "/home/dave/.config/blender/2.83/scripts/addons/AddRoutes/data.py", line 32, in <module>`
`    from . import g_vars`
`  File "/home/dave/.config/blender/2.83/scripts/addons/AddRoutes/g_vars.py", line 22, in <module>`
`    import rtmidi`
`  File "/home/dave/.config/blender/2.83/scripts/addons/AddRoutes/rtmidi/__init__.py", line 4, in <module>`
`    from ._rtmidi import *  # noqa`
`ModuleNotFoundError: No module named 'rtmidi._rtmidi'`

**Comment by imedina7** [comment]
It was a missing dependency problem, `sudo pip3 install python-rtmidi` solved the issue.

**Comment by EvanHaal** [comment]
How did you fix this exactly? Where do I write "sudo pip3 install python-rtmidi"
